language: java
env:
  global:
  - secure: q+fkZBCN8ET5RrgaG4RGt1t1aSjsL6LN6BSt/Yvx2H5a2DtGmNA/A/gcAEnKlyv0BgXAcrzAzCCIgXvt2P4om5DcBU/yOTEga+/46r7+iVnmfQGcW81NHQA1rlIYvuBqXGDo9yo1B3eRr8vTj3fzEE3K8jjchHQUlgRdUum3DNKeZwACodV2fpj9ZslyoX4HRpWg3ctqvB0R7/4NwtXnXrOw8hHDF8OrQK3JiCxAoZnA16/Fwc0d8yN4Or10N1XiWbNdLFek+Y3nVTdGRUZjsqp/VhvgIwzmtnuiCeF2iuMCpYy6C9SAFG4Tyn5VLmFzEqXMrbxuMBp8c2GCcFQb0jxEiWKsT0Nufqc1pYlUSl2S12D8yokEo5H9/NcH/2p2b5zqzcWzFe1c5YEn0Ktj8d/01GDYfkuPyoQ0UmjC6h68iozk5mogPT0t7eUf7i0wll72v4kGB2xOK3VY+53LA7DS+f/0HeDi47tXgPkA8bg2dGZTTD+JHXcqyMTt9Ey96a42cauLQ4PGfujc6fPJUw31sxx2IURj1USdxut/a5PEa+LL+xGrKKgOW4GMUwjrYMnLf9e3Y/uR4EoHmYYwsoNtD0g6bEt7C83JZrQd5Sp3mN6gEU0sjp2/iBPqS+tB3z6eRUur8ctnk6EC82WHmRwZHeoKLVOktAPCKumBnWY=
  - secure: 04af3/9b67O5xd1U8GDhCqRQedHM3RP5HokdsOwAe8vN3EyyyKWXQafBkKsPvmDh5Uu/CYQppOYS4pQxB9ikweTfj34DbyyxpqJmjYE4KFvdQuFd0msyXhLCg6xfvS4KO6zjUQ8/c3rNQap4hx/icQ50/NES4rkUkxIZ/VKQ4jPXcBzPegEC6Le50Vw2tR8FT4erdNuABnGf1WnWGUUa3i6xdQQPyw8kdTIun08HxE6M9F+JJRH8jH3b7KizQhGdACAk4fnCOmFSgu7pm6ACXRJYqAfg055i5mr77yZXfeUIcIY3l45uY1uR8sxEbLUE/KwwlLGLVZWDI4xU6JIGisbrmMce+vz6YKUT9gHF3iAEJ5e4N18nJcRyHVrqcuRzv5Py0rFPZ70dr7aW/tk0JrTz6+FZ4FNIOdvIQe4qWy2TVns0EkERdtYGTdsigWfa/sKF/P5+/2foUOlnR06p55NHpIjaHRKy/XFVV1gyURUlRUGExVoIMX21bAMxGYMFMH7LfddRsly028lXwibRMkQGBeyVRYKQmqJvN3mTPbuAWmZZdaVpqn1jkgETlT6/qz43zv9y8jAOzZ22SeHEXe3NiexChqkAJWIH3cBYshMhy8H1fmYAIVYHvI+BPsbi+qDYSnAlAUDqoLWXPAvWUX89dAIXYRNcKplzpFsjWvM=
  - secure: LhgEcPXC3lWlesziXDtT9tLnmgO3hTYpxIG8MsOYzdMOVsNpvdQ2mu2DKfW5pPATf7hvJm5pTShbm37MuPOt+HMa0KA4erBgfemKdjeUZO+XIzRzU0AcKfUAYmIPVAySpK7gVM3GQ8YCMAlVH0mwhw280RLuIOv8f61t77udFWm5UAdxP1N1V2WpafNII8T+thfgJjj/F8ryQI/r3lvSsX4VN8RIxSJSmJiSZuJq27C9CpkphL2sANhPuVSHE3WkNS1YCr0pnpoeEEJYabOqp5QtMhJ6WE8nfyk8imLDxiZ4miytN7odC1V/z8jqSDm+W0T/40ZVlyPG3CvtZxKm+zPonoi5fpf7bSFry6N9IXXqGdGj5mcXhntsA9J4gv3p1gFR87HaceD83Laz49fPAV5J4By37zLgWJZNjxNOd3GWV2KtqqA+yOMcf1YTWzIc9aP9j5bv0hUApPjZ075q42+fjGo2Yu0A32hYpSxiP1WIu5wag6+9IW0u9dZidBMCefDTG66DZ/BKMnKpRSt0//8TkeyoqiADJ8ZQbPN3sCtjvmZppe2CT7OhN6f4Goxd5PK2E2jHCgJW6naKcGJ61dceMahtvOKkY0jM3/iSOB4drIINm/JOzaiPV/oZhjBG5rjZ270dgCT4WOkxQPyHYGGgF1im1f4eA+AaE4oApDE=
matrix:
  include:
  - jdk: openjdk7
    services: cassandra
    script: "./scripts/verify.sh"
  - jdk: oraclejdk7
    services: cassandra
    script: "./scripts/verify.sh"
  - jdk: oraclejdk8
    services: cassandra
    script: "./scripts/verify.sh"
  - jdk: oraclejdk8
    sudo: required
    dist: trusty
    before_install: "./scripts/configure-apache-cassandra.sh"
    script: "./scripts/verify.sh"
  - jdk: oraclejdk8
    script: "./scripts/verify-embedded.sh"
after_success:
  - mvn clean test jacoco:report coveralls:report
deploy:
  provider: script
  script: "./scripts/deploy.sh"
  skip_cleanup: true
  on:
    branch: master
    jdk: oraclejdk8
