language: java
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
env:
  global:
    - secure: "q+fkZBCN8ET5RrgaG4RGt1t1aSjsL6LN6BSt/Yvx2H5a2DtGmNA/A/gcAEnKlyv0BgXAcrzAzCCIgXvt2P4om5DcBU/yOTEga+/46r7+iVnmfQGcW81NHQA1rlIYvuBqXGDo9yo1B3eRr8vTj3fzEE3K8jjchHQUlgRdUum3DNKeZwACodV2fpj9ZslyoX4HRpWg3ctqvB0R7/4NwtXnXrOw8hHDF8OrQK3JiCxAoZnA16/Fwc0d8yN4Or10N1XiWbNdLFek+Y3nVTdGRUZjsqp/VhvgIwzmtnuiCeF2iuMCpYy6C9SAFG4Tyn5VLmFzEqXMrbxuMBp8c2GCcFQb0jxEiWKsT0Nufqc1pYlUSl2S12D8yokEo5H9/NcH/2p2b5zqzcWzFe1c5YEn0Ktj8d/01GDYfkuPyoQ0UmjC6h68iozk5mogPT0t7eUf7i0wll72v4kGB2xOK3VY+53LA7DS+f/0HeDi47tXgPkA8bg2dGZTTD+JHXcqyMTt9Ey96a42cauLQ4PGfujc6fPJUw31sxx2IURj1USdxut/a5PEa+LL+xGrKKgOW4GMUwjrYMnLf9e3Y/uR4EoHmYYwsoNtD0g6bEt7C83JZrQd5Sp3mN6gEU0sjp2/iBPqS+tB3z6eRUur8ctnk6EC82WHmRwZHeoKLVOktAPCKumBnWY="
    - secure: "04af3/9b67O5xd1U8GDhCqRQedHM3RP5HokdsOwAe8vN3EyyyKWXQafBkKsPvmDh5Uu/CYQppOYS4pQxB9ikweTfj34DbyyxpqJmjYE4KFvdQuFd0msyXhLCg6xfvS4KO6zjUQ8/c3rNQap4hx/icQ50/NES4rkUkxIZ/VKQ4jPXcBzPegEC6Le50Vw2tR8FT4erdNuABnGf1WnWGUUa3i6xdQQPyw8kdTIun08HxE6M9F+JJRH8jH3b7KizQhGdACAk4fnCOmFSgu7pm6ACXRJYqAfg055i5mr77yZXfeUIcIY3l45uY1uR8sxEbLUE/KwwlLGLVZWDI4xU6JIGisbrmMce+vz6YKUT9gHF3iAEJ5e4N18nJcRyHVrqcuRzv5Py0rFPZ70dr7aW/tk0JrTz6+FZ4FNIOdvIQe4qWy2TVns0EkERdtYGTdsigWfa/sKF/P5+/2foUOlnR06p55NHpIjaHRKy/XFVV1gyURUlRUGExVoIMX21bAMxGYMFMH7LfddRsly028lXwibRMkQGBeyVRYKQmqJvN3mTPbuAWmZZdaVpqn1jkgETlT6/qz43zv9y8jAOzZ22SeHEXe3NiexChqkAJWIH3cBYshMhy8H1fmYAIVYHvI+BPsbi+qDYSnAlAUDqoLWXPAvWUX89dAIXYRNcKplzpFsjWvM="
    - secure: "WwRHn2P04tD5LibPHshL+yM1owpEs/+EWKdKgsSurj2oefAnSn90ZIUmdfQsNGWE0OjUibDhH/nX0IwvObRGGPJVDDgA+uHkTh09olK/m7/ByiloH18jeEGmA84eyRcKOhjvimepGhDUYtEyZFoBkIlBz2fmU+n4BmRhCD6w0dzLT3WVDsDtkA7iMT3F7Mg7Url0yjaFiMBFmNrV0PSZlOTFHkh4uUT4RqhC3/mMIPRUL8mLh5IoxJ3oHDpOhq3kGax17SBzIeMl3d5CJmKFN6p0Sn28zVnfNQzDZvledFzpD727jlbb5rBCjLqsFgTmZOdyFM15swu6/46DKsFmMH0rdjryPrxyhmUStP5vOeYiHBo1bz7z5pHwxz4dqYUmcyfHjbHcdgnEEbJEbMpz2nnGMpTvnmvFlvdGgW5zF72z8VXJZNh7E7YXe5FUSuAflIObFgW/3hdKNHWNdbCnau6GtwTV7IyGdtJKRii+LnWIa+nXw1kVGNFWNuDrS0csYfYrI4r9b9sLMzRkKzx7OSx96bG0pkgZT19AKcSP4Gv5LAmn4o+KoKv/+ULDimgGjhufX2v+Xx7usqWsE3T3842t251SjW7HchwD6plUvECKVJyWrYSse/1W4msVKej1YonxdsDDG5c3VidA+OebGj6jId6zRt9/oRU1F7barUA="
install: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - curl -Lo travis_after_all.py https://raw.github.com/dmakhno/travis_after_all/master/travis_after_all.py
  - mvn test
after_success:
  - python travis_after_all.py https://api.travis-ci.com
  - export $(cat .to_export_back)
  - |
      if [ "$BUILD_LEADER" = "YES" ]; then
        if [ "$BUILD_AGGREGATE_STATUS" = "others_succeeded" ]; then
          echo "All jobs succeeded!"
          echo "Deploying..."
          mvn deploy --settings settings.xml -DskipTests=true -B
        else
          echo "Some jobs failed"
        fi
      fi
after_failure:
  - python travis_after_all.py https://api.travis-ci.com
  - export $(cat .to_export_back)
  - |
      if [ "$BUILD_LEADER" = "YES" ]; then
        if [ "$BUILD_AGGREGATE_STATUS" = "others_failed" ]; then
          echo "All jobs failed"
        else
          echo "Some jobs failed"
        fi
      fi
after_script:
  - echo leader=$BUILD_LEADER status=$BUILD_AGGREGATE_STATUS